Feat/cta
unepwcmc/ecosystemassessments-wordpress pull request #3
Opened 2021-03-02 17:21 UTC by stanleypliu

Style 'Contact Us' CTA block that appears on multiple pages. 

Desktop:
![Screenshot 2021-03-02 at 17 18 54](https://user-images.githubusercontent.com/53650048/109687662-5f009680-7b7b-11eb-9a20-2c5b520b4789.png)

Mobile:
![Screenshot 2021-03-02 at 17 19 20](https://user-images.githubusercontent.com/53650048/109687712-6de74900-7b7b-11eb-800d-4bab3f167d49.png)

**Notes**

Branched from `feat/featured-link-component`
I've changed the site width to 1248px to reflect the design as well as making the button text for the `button_secondary` mixin responsive.

2021-03-02 18:23 UTC, nym1k requested changes

2021-03-02 18:23 UTC, nym1k commented on content/themes/ea/src/scss/components/_cta.scss
>    position: relative;
Background:  $color-primary can be deleted from the .cta-block as well

2021-03-02 18:23 UTC, nym1k commented on content/themes/ea/src/scss/components/_cta.scss
> +    margin-right: auto;
You'll need to set the margin-left to 0 here as well

2021-03-03 09:37 UTC, stanleypliu commented on content/themes/ea/src/scss/components/_cta.scss
> +    width: calc((5 / 12) * 100%);
![Screenshot 2021-03-03 at 09 24 43](https://user-images.githubusercontent.com/53650048/109783797-4b4c4300-7c02-11eb-9fd2-7db3a6795b97.png)

That might be true for the box as a whole, but this width concerns the width of `.cta-block__content` which is the content inside the box as shown, and then padding is added on top of that to reach the final width of the box. The screenshot shows it as being closer to something like 5 / 12

2021-03-03 10:01 UTC, stanleypliu commented on content/themes/ea/src/scss/components/_cta.scss
>    position: relative;
I've deleted the background, but I've added a border for the block if there isn't an image because the background is white, and without it the CTA just fades into it without being noticeable.

2021-03-03 10:16 UTC, stanleypliu commented on content/themes/ea/src/scss/components/_cta.scss
> +    bottom: calc(var(--border-height) * -1);
Thanks, good tip

2021-03-08 09:51 UTC, nym1k requested changes

2021-03-08 09:51 UTC, nym1k commented on content/themes/ea/src/scss/components/_cta.scss
> +  @include font_heading-cta;
Unless it's a very specific use case, we shouldn't be making new font_heading mixins, and should be using the ones available to us. (I can see why you would have done it though)

I think we should make this the font_heading-2 mixin, and any text that is font-size: 40 and line-height: 45 can be font_heading-3

2021-03-08 10:38 UTC, merged